version: 0.0
os: windows
files:
    - source: /
      destination: /home/app
    - source: /appserver
      destination: /home/app/appserver
    - source: /utils
      destination: /home/app/utils
    - source: /crawl
      destination: /home/app/crawl
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/app
      pattern: '**'
      owner: aws_redoundo
      group: deploy-group

hooks:
    BeforeInstall:
        - location: scripts/before-install.ps1
    AfterInstall:
        - location: scripts/after-install.ps1 