FROM ubuntu:latest

WORKDIR /django-server

COPY djangoapp /django-server/djangoapp
COPY djangoserver /django-server/djangoserver
COPY server-nginx.conf /django-server/etc/nginx/sites-available/server-nginx.conf
COPY sample /django-server/sample
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY manage.py /django-server
COPY .env /django-server

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y upgrade python3
RUN apt-get -y install python3-pip
RUN mkdir django-server
RUN rm /usr/lib/python3.12/EXTERNALLY-MANAGED
RUN apt-get -y install nginx supervisor pkg-config libmysqlclient-dev mysql-client
RUN ln -s /django-server/etc/nginx/sites-available/server-nginx.conf /etc/nginx/sites-enabled/server-nginx.conf
RUN pip3 install django-cors-headers mysql-connector-python djangorestframework Django gunicorn pytz APScheduler PyJWT firebase-admin mysqlclient python-decouple requests python-dotenv

ENV MYSQL_DRIVER_NAME=mysql+mysqlconnector
ENV DATABASE_PORT=7007
ENV DATABASE_NAME=culture_center_db
ENV DATABASE_USERNAME=culturecenter
ENV JWT_ACCESS_EXPIREDAT=60000
ENV JWT_REFRESH_EXPIREDAT=70000
ENV JWT_ISSURE=cultureCenterServer
ENV JWT_ALGORITHM=HS256

CMD ["supervisord", "-n"]