FROM ubuntu:latest

WORKDIR /java-server

COPY src /java-server
COPY server-nginx.conf /java-server/etc/nginx/sites-available/server-nginx.conf
COPY sample /java-server
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN apt-get update
RUN apt-get -y upgrade
RUN mkdir java-server
RUN apt-get -y install openjdk-17-jdk nginx supervisor pkg-config libmysqlclient-dev mysql-client
RUN ln -s /java-server/etc/nginx/sites-available/server-nginx.conf /etc/nginx/sites-enabled/server-nginx.conf

ENV MYSQL_DRIVER_NAME=mysql+mysqlconnector
ENV DATABASE_PORT=7007
ENV DATABASE_NAME=culture_center_db
ENV DATABASE_USERNAME=culturecenter
ENV JWT_ACCESS_EXPIREDAT=60000
ENV JWT_REFRESH_EXPIREDAT=70000
ENV JWT_ISSURE=cultureCenterServer
ENV JWT_ALGORITHM=HS256

CMD ["supervisord", "-n"]