FROM ubuntu:latest

WORKDIR /java-server

COPY jar/javaserver-0.0.1-SNAPSHOT.jar /java-server
COPY server-nginx.conf /java-server/etc/nginx/sites-available/server-nginx.conf
COPY sample /java-server
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN apt-get update
RUN apt-get -y upgrade
RUN mkdir java-server
RUN apt-get -y install openjdk-17-jdk nginx supervisor pkg-config libmysqlclient-dev mysql-client
RUN ln -s /java-server/etc/nginx/sites-available/server-nginx.conf /etc/nginx/sites-enabled/server-nginx.conf

VOLUME /var/log/spring_boot
VOLUME /var/log/nginx

HEALTHCHECK --interval=50s --timeout=10s --start-period=30s --retries=3 CMD curl -f http://localhost:8079/actuator/health || exit 1

CMD ["supervisord", "-n"]