[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true


[program:spring-boot]
command=java -jar /java-server/javaserver-0.0.1-SNAPSHOT.jar
autostart=true
autorestart=true