# Generated by Django 5.0.4 on 2024-06-03 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='crawleddate',
            field=models.DateTimeField(db_column='crawledDate', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='fcmtoken',
            field=models.CharField(blank=True, db_column='fcmToken', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='registerdate',
            field=models.DateTimeField(db_column='registerDate', default=django.utils.timezone.now),
        ),
    ]
