name: culture-center-server deploy
on:
  push:
    branches:
      - "server"

permissions:
  contents: read

jobs:
  deploying:
    runs-on: codebuild-culture_center_build-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        run: |
          python install pip
          pip install APScheduler Flask PyJWT SQLAlchemy firebase-admin mysql-connector-python

      - name: run crawling docker
        run: |
          cd /crawl
          docker build -f Dockerfile
          docker run -d -e DATABASE_HOST=${{secrets.DATABASE_HOST}} DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}} --name crawling
