name: culture-center-server deploy
on:
  push:
    branches:
      - "server"

permissions:
  contents: read

jobs:
  deploying:
    runs-on: window-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0

      - name: build python
        run: |
          python install pip
          pip install -e .

      - name: run crawling docker
        run: | 
          cd /crawl
          docker build -f Dockerfile
          docker run -it -d -e DATABASE_HOST=${{secrets.DATABASE_HOST}} DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}}
