name: github action and docker ci/cd
on:
  push:
    branches:
      - "ml"
    paths:
      - "train_sample.json"

permissions:
  contents: read

jobs:
  ci-cd:
    name: ci-cd jobs
    runs-on: window
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}

      - name: ml-docker-ci-cd
        if: contains(${{github.ref}}, 'ml')
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build https://github.com/redoundo/Crawling.git#ml
          docker run -d -e DATABASE_HOST=${{secrets.DATABASE_HOST}} DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} --name cicd
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ml-ci-cd:only
          docker commit cicd ghcr.io/${{ github.actor }}/only
          docker push ghcr.io/${{ github.actor }}/only
