name: culture-center-server deploy
on:
  push:
    branches:
      - "server"

permissions:
  contents: read

jobs:
  deploying:
#    runs-on: codebuild-culture_center_build-${{ github.run_id }}-${{ github.run_attempt }}
    runs-on: window-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0

      - name: build python
        run: |
          python install pip
          pip install pip APScheduler Flask PyJWT SQLAlchemy firebase-admin mysql-connector-python

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#      - name: zip python
#        run: tar -a -c -f culture_center.zip
#      - name: Upload to S3
#        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://culture-center-bucket/$GITHUB_SHA.zip

      - name: run crawling docker
        run: | 
          cd C:/Users/admin/flaskserver/server/app/crawl
          docker build -t crawler -f Dockerfile .
          docker images
          docker run -d -e DATABASE_HOST=${{secrets.DATABASE_HOST}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} -e DISCORD_WEBHOOK_URL=${{secrets.DISCORD_WEBHOOK_URL}} crawler
